# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.12.0"

private_lane :commit do |options|
  if options[:m] # There was a commit message
    sh("git add -A")
    sh("git commit -a -m '" + options[:m] +"'")
    if options[:b] # specify a branch to push to
      push_to_git_remote(local_branch: options[:b])
    else # or default branch is master
      push_to_git_remote
    end
    desc "Pushed commit to branch options[:b]"
  end
end

platform :android do

  before_all do
    # Make sure no debugger statements were left in our code 
    # ensure_no_debug_code
    # Make sure there are not uncommitted changes
    # ensure_git_status_clean
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end


  lane :beta do |options|
    if options[:m]
      commit(options)
    end

    desc "Compiling a new build for Android ..."
    cordova(
      platform: 'android',
      release: false
    )

    crashlytics(
      apk_path: './platforms/android/build/outputs/apk/android-debug.apk',
      api_token: "b0510b6b26fe11d43115f7fb04d744bacc44a0f9",
      build_secret: "942d313429ea10c092669c1e842932e401f7d21448acc7fec67975475a9c1df1",
      notifications: true,
      debug: true
    )
      
    rocket
    say "Brad you rocked another android deployment"
  end
end

platform :ios do
  before_all do
    # Make sure no debugger statements were left in our code 
    # ensure_no_debug_code
    # Make sure there are not uncommitted changes
    # ensure_git_status_clean
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."  
    cocoapods(
      use_bundle_exec: false,
      podfile: "./platforms/ios/Podfile"
    )
  end

  desc "Submit a new Beta Build to Hockeyapp"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    app_name_sanitized = 'Apparent'
    ios_project_path = "platforms/ios/#{app_name_sanitized}.xcodeproj"
    increment_build_number(
      xcodeproj: ios_project_path
    )

    # build your iOS app
    cert
    sigh(
      adhoc: true,
      force:true
    )
    gym(
      workspace: "platforms/ios/#{app_name_sanitized}.xcworkspace",
      clean: true,
      export_method: "ad-hoc",
      scheme: app_name_sanitized
    )

    crashlytics(
      api_token: "b0510b6b26fe11d43115f7fb04d744bacc44a0f9",
      build_secret: "942d313429ea10c092669c1e842932e401f7d21448acc7fec67975475a9c1df1",
      notifications: true,
      debug: true
    )

    rocket
    say "Brad you rocked another i o s deployment"
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

end

